Blog 23 autenticacion implementar login
QSoftwareBo/Blog pull request #12
Opened 2021-11-22 15:46 UTC by OmarHQ

Contiene Commits de:
Blog 31: Crear Formulario para Login
Blog 32: Crear control y model para Login de Usuario
Blog 33: Comprobar sesión al momento de ingresar al Sistema
Blog 34: Validar vigencia de sesion para los controladores (plus vistas)

2021-11-22 15:51 UTC, OmarHQ commented
Observacion: Siendo Complemetarios, la vigencia de sesion para el Usuario y control de sesión para el resto de archivos, el Blog 34 contiene de forma interna al Blog 33

2021-11-24 14:37 UTC, lquenta requested changes
favor revisar las observaciones y solucionarlas en este mismo branch

2021-11-24 14:37 UTC, lquenta commented on Login.php
> +		//Por ahora sólo se utiliza un if para el password NO ENCRIPTADO
poner este tipo de pendientes con la etiqueta TODO, por ejemplo
//TODO:Por ahora sólo se utiliza un if para el password NO ENCRIPTADO

2021-11-24 14:37 UTC, lquenta commented on views/view.Login.php
> +						<input class="password_btn" type="password" id="password" name="password" placeholder="Password" required>
no existe class css para este elemento

2021-11-24 14:37 UTC, lquenta commented on views/view.Login.php
> +						<input class="password_btn" type="password" id="password" name="password" placeholder="Password" required>
password_btn

2021-11-24 14:37 UTC, lquenta commented on views/view.Login.php
> +						<input class="usuario" type="text" id="nombre" name="nombre" placeholder="Ingrese nombre de Usuario" required>
existe class usuario en el css ?

2021-11-24 14:37 UTC, lquenta commented on views/view.ListadoPublico.php
> +    <input type="button" onclick="location.href='../models/model.CerrarSesion.php'" value="Cerrar Sesion">
los botones de control general como salir sesion deben ir en un control comun que se llame en todas las vistas, sino repetiremos codigo

2021-11-24 14:37 UTC, lquenta commented on views/view.ListadoPublico.php
> +    <input type="button" onclick="location.href='../models/model.CerrarSesion.php'" value="Cerrar Sesion">
puede ser un header

2021-11-26 14:25 UTC, lquenta approved these changes
cambios aprobados

2021-11-26 14:25 UTC, merged