Blog 38 validacion roles usuario
QSoftwareBo/Blog pull request #14
Opened 2021-11-26 14:48 UTC by OmarHQ

Blog 40 - Validacion de vistas según Rol de Usuario

2021-11-30 17:09 UTC, lquenta requested changes
Favor mover los archivos de Cerrar Sesion y comprobacion de rol fuera de la carpeta modelos dado que no afectan ni solicitan info de la BD

2021-11-30 17:09 UTC, lquenta commented on models/model.CerrarSesion.php
> -
no entiendo muy bien por que este archivo y funcionalidad de cerrar sesion esta en los modelos, afecta de algun modo la base de datos? @OmarHQ

2021-11-30 17:09 UTC, lquenta commented on models/model.ComprobacionRol.php
> +<?php
de la misma manera, pienso que estos archivos deberian estar a nivel controlador no en el modelo, los modelos afectan la base de datos

2021-11-30 17:26 UTC, OmarHQ commented
Cambios realizados para la funcion de cierre de sesion, establecido ahora como Controlador y fuera de la carpeta de Modelos. 
Se vio por conveniente además realizar algunas modificaciones en funciones de restriccion que podrían verse afectadas.

2021-12-14 17:59 UTC, lquenta approved these changes

2021-12-14 17:59 UTC, merged